version: "3"
services:
    client:
        build: ./client
        ports:
            - 3000:3000
        volumes:
            - ./client/src:/usr/src/client/src
            - ./client/public:/usr/src/client/public
        links:
            - api
        expose:
            - 3000
    api:
        build: ./api
        ports:
            - 9000:9000
        volumes:
            - ./usr/src/api:/usr/src/api/src
        expose:
            - 9000
